version: '3.8'
services:
    tethysdb:
        image: mysql:8.0.25
        container_name: tethysdb
#        tty: true
        restart: always
        environment:
            MYSQL_DATABASE: 'scorecard'
            MYSQL_USER: 'scorecard'
            MYSQL_PASSWORD: 'scorecard'
            MYSQL_ROOT_PASSWORD: 'threeblindmice'
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d/:ro
            - /opt/apps/tethysdb:/var/lib/mysql
        ports:
            - 3306:3306
    tethysui:
        image: tethysui
        container_name: tethysui
#        tty: true
        ports:
            - 80:8080
        restart: always
        depends_on:
            - tethysdb
